# Generated by Django 4.2.1 on 2023-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot', models.CharField(max_length=50)),
                ('drone_model', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('flight_duration', models.IntegerField()),
                ('weather', models.CharField(max_length=20)),
                ('crash_unexpected', models.BooleanField(default=False)),
            ],
        ),
    ]
