# Generated by Django 4.2.1 on 2023-08-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dronelog', '0002_dronemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='droneflight',
            name='drone_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dronelog.dronemodel'),
        ),
    ]
