# Generated by Django 4.2.1 on 2023-08-06 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dronelog', '0003_alter_droneflight_drone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='droneflight',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
